</$objtype/mkfile

LIB=libstr.a
OFILES=strstubs.$O

</sys/src/cmd/mklib

CC=pcc
LD=pcc
INCLUDES=-I../../byterun
CFLAGS=-FV -c -D_POSIX_SOURCE -D_BSD_EXTENSION $INCLUDES
LDFLAGS=

ROOT=/home/pad/plan9/ROOT

install:V: libstr.a
	cp libstr.a $ROOT/usr/local/lib/ocaml
