* Big plan

** Overview

# finish backport arm (fix current segfault a.out), compile efuns on plan9!
# release code and SEMI LP of ocaml-light, 
# add/backport cool/recent features (e.g., let*, deriving, typeclasses! or go interfaces in ocaml? :))
# leverage bench and examples/, add amd64/arm64/riscv
# and even use goken9cc toolchain instead of gcc -m32 later!

** Later

*** LATER retarget plan9 assembly (arm and x86) so can build OCaml binaries
for my plan9 raspberry or for my plan9 qemu

*** LATER backport arm64 backend, so can produce arm64 Linux binaries!!!
#note that producing arm32 binaries is fine too and might be enough
# and simpler for now. The slowdown of arm32 on arm64 is probably fine
#leverage arm porting? hopefully internal APIs didn't change too
# much (Xavier Leroy usually does not change a lot the APIs)

arm64 code that was added late in 4.xx too different from 1.07?

*** LATER backport amd64 backend too!
right now it's just asmcomp/i386

*** LATER try use mips backend with 5i?


* Last

** Last1

*** WEIRD: type-directed field access didn't work in rare case
in Codegen5.ml for node.n_loc when added the same
module T = Types  alias in Codegen.ml (which is open'ed 
in Codegen5.ml) then error on n_loc (even if node is typed
with (node : 'a T.node) few lines before.

weird that an open in a separate file has an impact on another module.
Note that no Codegen.mli so if had .mli probably would not happen.
Still would be good to figure out why the code didn't work, why
not able to resolve the type of node in the presence of those
multiple module aliases and open.

*** RELAX Hashtbl.find_opt

*** handle |Failure s | Sys_error s -> <stuff>
allow matched equal var in Or pattern

and fix back the code I originally rewrote in xix, see
(* ocaml-light: ... *) comments

*** RELAX backport ocamlc -where
but not -I +xxx, not worth it

*** backport "remember" C libs in .cma
ocaml 3.00 changes:
- Libraries (.cma and .cmxa files) now "remember" C libraries given
  at library construction time, and add them back at link time.
  Allows linking with e.g. just unix.cma instead of
  unix.cma -custom -cclib -lunix

*** fix ocaml-light -threads and reference to undefined global Stack
found when using ocamlc -threads in xix/mkfiles/mkconfig.light
which is needed for access to Event.channel type

*** -----------------------------------------------

*** resume port to plan9 now that I can run plan9!!!!
see special branch in ocaml-light-old

and I can especially run rio-ocaml!!! and test the build
of rio-ocaml and draw-ocaml!!

and also efuns in plan9!

*** --------------------------------------

*** BIG: backport Int32.ml, Int64.ml (requires custom blocks)
#useful for ogit port to ocaml-light and also for o5l ELF linker

**** Int32.ml/... modules
https://github.com/ocaml/ocaml/commit/15f811734e33051581406135d05ecf9769a1f031#diff-d6d565022f96e25bf90fb73a6efcad17c2035dd8614132698b607b76d12f44fe


**** add Int32.t and Int64.t first step
34a71202962072f30f27882498cb7e745b5dafd7

**** need first?(BIG) introduction of Custom blocs 
9e206909f48d5d2579b6ec17764d3273df23ff08 (10 Feb 2000)

**** need first finalise.c?
0a2021e98672e198283f6aa2e0df16aeac4d7d71 (7 Jan 2000)
117525ed94a7cb45fbf464284eb133655be0e0a3 (11 Jan 2000)

**** need first SIZEOF_INT == ...


**** previous changes to str ??

**** previous changes to systhreads?

**** extend IO.ml with ocaml-light support for Int32.ml Int64.ml
or get rid of IO.ml

*** more type-directed disambiguation

at least handle when one of the field is qualified, apply
same qualifier to the other?

  let conf : Preprocessor.conf = { Preprocessor.
    defs = !macro_defs;
    (* this order? *)
    paths = system_paths @ List.rev !include_paths;
    dir_source_file = Fpath.v (Filename.dirname !infile);
  }
or better directly
 let conf = Preprocessor.{ defs = ... }

*** make promote and start to use the { lbl } shorthand notation
feature in the code of ocaml-light itself!

*** ocaml-light: backport arm ocamlopt

**** try compile bytecode with armhf gcc too? segfault because
of ARCH_SIXTYFOUR and ARCH_32 issue again?

**** apply diff on roots.c and other changes in 
66ae9423a784fbc4d35b794906a4dee705afccf2
compared to current state in asmrun/ especially

**** gdb hello.out produced by arm ocamlopt
caml_main

**** notes
can generate EABI arm32 that can run on my astra ??

commit 5732a03e6599b47fe3f581f65ccd37395d6421c8
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Tue Mar 31 09:45:55 2009 +0000
    Updated ARM port to new ABI (EABI), with software floating-point.



commit 66ae9423a784fbc4d35b794906a4dee705afccf2 (HEAD)
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Thu Oct 15 16:10:53 1998 +0000
    Portage ARM

commit fca1be1fddcd0d7a80a16f2282b6595e484556ae
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Wed Oct 14 17:08:57 1998 +0000
    Suite du portage ARM

commit 281583d13d79a55536faf07a50c9777abb5b9188
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Sat Oct 10 14:56:53 1998 +0000
    Portage ARM

commit 57c704d7390c4d92dfce5666c76f263ed414a687
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Fri Oct 9 14:43:30 1998 +0000
    Portage ARM -- premier jet

**** later: Fix Proc.ml to use Config.assembler or something instead of
hardcoded use of "as"
update: actually it's in arm/proc.ml so it's fine



** Last0

*** read camlboot and other papers on remarkable

*** make sync

*** make sync_c
pb with config.h and md5sum entries
regenerate from scratch? just skip this file?

*** FUN read camlboot paper?

*** RELAX add -version to optmain.ml too

*** RELAX get tools/debugger/ to work! make does not even compile
and regression tests? actually run and test it?

Env.summary not found? because I've deleted the code before.
Not sure why, maybe to simplify for OCaml.nw

make sync first

*** RELAX make dune file for tools/debugger/


*** multi-arch: mips, arm and more later

**** FUN try make native arm to work! how to test? qemu? raspberry pi?
again good intermediate step towards fixing plan9 on raspberry pi?

**** FUN Dockerfile.mips and configure
alt: find a way to make it easy to cross compile and use wrapped true trick
 or something but would require too much change. The poor's man functor
 approach of symlink is maybe better (and fit more ocaml-light anyway)


*** can actually link an ocaml(opt) via dune? can I make an executable section?
in driver/dune?

*** RELAX compile more ocaml-light/examples/
#!!!good testbed to check if ocaml light expressive enough for those examples
# whether we need OO, functors, labels, etc!
# and good testbed towards getting also xix to compile with ocaml-light!!!

**** can look at "Le langage Caml" book pour replonger dans ces programmes :)

**** restore doctor and docteur test, weird diff in Docker vs local

*** Multi-platform build of ocaml-light

**** try run ocaml-light on both macs, pb on grey one?
proof we don't need all those old Makefile.mac

**** try compile ocaml-light on windows! with mingw!
how to check this in CI? see build-windows.yml from semgrep?
good to imitate?

proof we don't need all those old Makefile.nt

**** try compile ocaml-light on windows and macbook x86_64
bonus: make also asmcomp/ and native programs run with -m32
bonus: build/test in CI! macos-latest, windows-latest, ubuntu-latest

start use jsonnet?

*** RELAX handle the .c.rej of alloc_small in untracked files
now that has good test infra, can start to do fearless refactoring/changes

*** less: fix the weird failwith "select_floatarith"
+ );
+
+  select_floatarith = (fun _ ->  failwith "select_floatarith");
+  select_push = (fun _ -> failwith "select_floatarith");
+ }
 
*** -------------------------------------------------------------

*** LATER: make it work on plan9
and then finish draw port so can then port ocaml-elm-playground to also
work on plan9 and run ocaml games on plan9! like rolling moon on plan9 :)

*** LATER: integrate zamcov in ocaml-light and its bytecode interpreter?
can be nice intermediate step to byterun/ ? or an alternative complementary
path to solidy byterun/ understanding?

*** LATER: what about the paper that tried to reboostrap OCaml?
can take code from there too?
camlboot interp? same approach?

*** LATER: add js_of_ocaml old simple version?

*** LATER: add wasm_of_ocaml?


** Internals

*** refactoring

**** less: remove Ident.xxx that are really a Map?
get rid of lots of code in Ident.ml?

actually I think he did that in more recent versions of ocaml,
even maybe in 1.07?

**** EASY delete Tmty_ident?
can remove more code?

**** get rid of mtype.ml

**** ???? type patterns? introduce elt in new_env!

**** EASY rename Env.modules -> Env.module_type and Env.components -> Env.module no?

*** checking

**** still? fix the warnings reported by ocaml 4.02
git stash apply!

**** less: forward port things fixing shift/reduce conflicts?
ocaml 4.00 has 0 conflicts

*** lots of boilerplate, how can factorize? all those enter_xxx, find_xxx,
a bit ugly no? typeclass can help? deriving?

** Still?

**** less: study diff between old and new typechecker?

 type type_expr =
-    Tvar of type_variable
+  { mutable desc: type_desc; 
+    mutable level: int }
+
+and type_desc =
+    Tvar
   | Tarrow of type_expr * type_expr
   | Ttuple of type_expr list
-  | Tconstr of Path.t * type_expr list
-
-and type_variable =
-    { mutable tvar_level: int;
-      mutable tvar_link: type_expr option }
+  | Tconstr of Path.t * type_expr list * (Path.t * type_expr) list ref
+  | Tnil
+  | Tlink of type_expr

+exception Cannot_expand
+exception Nonlinear_abbrev
+exception Recursive_abbrev


**** strictopt?
-type let_kind = Strict | Alias
+type let_kind = Strict | Alias | StrictOpt

* Components

** CMM:

*** cmm: use and improve cmm (useful for tiger?)

**** merge latest parsecmm stuff from ead8077daec521ef4d82697c10450087a1e74087^ ?
a few changes
alt: produce a diff_testasmcomp_latest?

**** LATER: codegraph on it! can't reduce cmm/codegen dependencies to less files in asmgen/?

** ocamldep

*** RELAX ocamldep does not handle correctly nested modules and
make Cap.cmo to depend on Console.cmi and FS.cmi incorrectly.
apparently only if the Console.ml file exist; it does not
create a dep from Cap.cmo to Process.cmo

and restore the Cap.Console and Cap.FS instead of _ suffix

see b81eec604036157120e5d622e0e6410d49fbf61c nouveau ocamldep using parser (Jan 1999)

** ocamllex

*** LONG add support for 'as' in ocamllex, just port enough for as feature
too complex? diff too big?
and revert back the changes in mk and rc and more
=> can hope to also compile the rest of xix with ocaml-light
(macroprocessor, assembler, etc.)


** Debug tools

*** backport Printexc.raw_backtrace so can get working Exception.ml

*** include diffs that help the debuggability of ocaml

commit a843096a997d0a2914b8cbabd952e4a230d07598
Author: Damien Doligez <damien.doligez-inria.fr>
Date:   Mon Apr 3 08:34:22 2000 +0000

    codes pour faciliter le debug

commit bad71c148081a820604b9901300a5b8e2b730a95
Author: Damien Doligez <damien.doligez-inria.fr>
Date:   Mon Nov 8 17:05:45 1999 +0000

    ajout heap_check en mode debug

commit 5674cf35c8d59cd19bb93a39542dfad1e7d9ac9e
Author: Damien Doligez <damien.doligez-inria.fr>
Date:   Mon Nov 8 17:02:14 1999 +0000

    ajout heap_check



* Infra

** Test infra

*** build-dune.yml in CI?
use setup-ocaml too? see hello-world-ocaml?

*** less: testasmcomp/ fixing

**** actually run the testasmcomp/ stuff? feed with different integers the tests?

**** test infra here? just test that compiles? no comparison to expected result?
was just used when developing a new backend by Leroy?

**** less: fix testasmcomp/arith.out ? infinite loop? CMM bug?

**** look also latest testsuite/asmcomp/ and copy the Makefile
that actually run the test?

*** still? find 32 bits for building ocaml-light on 32 bits arch in GHA
need to use qemu in GHA? like for our docker arm?

https://github.com/marketplace/actions/setup-alpine-linux-environment

*** use ocamlc.opt and ocamlopt.opt on everything? excellent test case!

*** is ocamldebug and the other tools/ working
check in CI again!

*** run the benchmarks too in test/? not just the tests
take the shootout benchmark? the programs pass with ocaml light?
(see also mincaml/shootout)

'make bench' in test/

*** less: add test linking with str and unix, and check regression
sys_errlist

actually had another problem later when linking with ocamlopt so
need test that use both ocamlc and ocamlopt linking to str and unix

*** less: add test in make test in myocaml for -lstr and -lunix with ocamlopt
and should show problem that I needed the -lunixopt trick

*** WEIRD fix memory corruption errors in 'make test' when running under Nix!
use valgrind locally? asan?
try to reproduce locally by using -fsanitize=address ?
find the CFLAGS used in Nix?

*** what about tests/Moretest/?

*** what about ocaml 3.01 tests/testinterp/ big list?
or even 4.14 testsuite/lib/

*** nix: restore nix-test for ubuntu/macos and full test for ubuntu-only

*** add GHA check for arm, does ocamlopt actually work?

*** include tests/ from csl/ and ocaml examples from caml light?
(that have been updated to ocaml 3.08 by leroy on their distrib/contrib/
I think)
=> more tests

** Build infra

*** less: extend configure with -as -aspp
so can configure for -m32 from the configure line

*** less: fix the many warnings in byterun/ from gcc and clang

*** can it compile when boot/ocamlc CAMLC is the OCaml 4.02.3?
then add this check also in CI! so upward compatible!

*** less: add -no-pie to remove some warnings

*** less: 40 shift/reduce conflicts in ocaml-light/parsing/parser.mly?
same with 1.07? 49 actually (maybe in OO code)

*** WEIRD: why can't make byterun/ work with -m32?

*** WEIRD: why nix-shell --pure can't build fib.out?
-lgcc not found ???

** Dev Infra

*** still? resume semgrep.yml, need more recent ubuntu and can remove cron too

** Devops

*** less: optimize docker image size by using multi-stage built like in Semgrep
otherwise takes forever to push (and I guess also to download)

before: 258MB

*** less: push docker automatically in CI after each master merge
try generate token instead of using password
add secrets in settings of project?

** Bench infra

*** bench: compare my ocaml 1.07 with ocaml 4.00? 
try on syncweb? faster?

* Later

** ocaml-light and xix

*** LATER: try my xix/windows/ rio port to plan9 using ocaml-light compiled

** Ports

*** finish portage arm

commit 66ae9423a784fbc4d35b794906a4dee705afccf2
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Thu Oct 15 16:10:53 1998 +0000

    Portage ARM

05627e0de4a50067f36d1eca9dcc9ebd5736c3f8
new ARM backend, backtrace, float, many stuff

*** LATER: add arm tests too

*** LATER: add amd64 generation? and arm64?
this was added recently; good test whether the code change that much

*** LATER: try compile again byterun/ for plan9! with kencc

*** LATER backport riscv support! so can run on plan9-riscv


** small features

*** LATER: automatic -cclib -lunix when adding unix.cma
backport which commit?

a la Go?

*** less: backport -nostdlib
update: I now use regular ocaml for the -nostdlib in xix, not
 ocaml-light, so less need for the feature in ocaml-light itself

but -nostdlib actually control the load_path? not whether stdlib.cma
is loaded or not? 
-nopervasives control stdlib.cma?

-nopervasives is needed to compile stdlib.ml itself, otherwise
 infinite recursion; to break the recursion we need -nopervasives

-nopervasives control the implicit open Stdlib which then requires
 an existing stdlib.cmi

-nostdlib control the load path or where to find the list.cmi,
 array.cmi and of course also stdlib.cmi

** remove stuff in OCaml to simplify

**** EASY less: remove or, and infix operator (use || and &&)

**** EASY less: get rid of type x = y = z
it's confusing anyway

**** less: remove tbl? just use map?

**** remove terminfo

**** remove stdlib/stream.ml?


** add stuff not in ocaml 

*** FUN add typeclasses!
or go directly to implicits?

http://okmij.org/ftp/Computation/typeclass.html

http://www.haskellforall.com/2012/05/scrap-your-type-classes.html

use implicit proposal syntax?
https://github.com/ocamllabs/ocaml-modular-implicits/commit/65a9ac20406833ba0d420fbe382ece17edf037bc

typing haskell in haskell for tutorial?

=> use in fork-ocaml itself, e.g. no more
duplicated names such as Subst.value_description and 
Subst.type_declaration, can have just Subst.subst 
with different instances of Subst! overload!
all those repeated names are useless.

*** an ocaml preprocessor! with unicode and mixfix a la Agda!
need update also efuns and codemap
see parsing mixfix paper in downloads.

*** FUN add deriving! or better, template haskell?
at least deriving!

and at least my xxx_of_v (or if have overloading
metaocaml_of !)

=> use in fork-ocaml itself, remove lots of boilerplate,
e.g. Subst.type_expr, essentially a visitor with just
a special case for Tvar ! the rest is boilerpate

*** later later

**** add attributes?

**** add error messages of julien

**** other cool but simple and orthogonal features?
stuff that will factorize code!
e.g. auto generate dumpers, visitors.
If have visitor then can rewrite some boilerplate code, e.g.
simplif.ml.

would be good to have delta programming, to express how to pass
from parsedtree.mli to typedtree.mli, because very very similar
(or just autogenerate via a script? :) )


* Backports

** Library
would be good to port to latest convention so caml_xxx 
so at least easy to get library from recent ocaml versions
working also under ocaml 1.07

*** Unix.realpath!
hmm but primitives are hard! need to promote, so better wait we have a few of them


*** less: add int32 and int64? used by IO.ml, OCaml.ml, etc. ?
seems complicated, better now

*** less: still? backport int32 and int64? for ogit and read_real_i32 function?
just that?
or simpler to just move code in version_control/index.ml for now

*** Arg.align

*** List.iteri

** Typechecker

*** leverage type annot to avoid having to qualify fields
so let foo (x : Bar) =
   x.fld
without needing x.Bar.fld

*** support for qualifier just for first field that propagates to
other fields so can do

{ Xxx.foo = 1; bar = 2; ... } without having to repeat Xxx (which helps
to avoid some open)

just cherry pick the patch that did that in original ocaml

*** support { x; y } when x and y are locals


** Compiler (checks and error messages)

*** TODO warnings to backports

Warning 26: unused variable t.

*** improve error messages

File "asmcomp/selectgen.ml", line 297, characters 1-19293:
Some labels are undefined
with no explanations of the labels...

File "typing/typecore.ml", line 246, characters 2-7965:
Warning: this pattern-matching is not exhaustive
with no explanations of the cases...

error for .mly are reported for the .ml. Support #line?

*** "Some labels are undefined" error
well nice, which one! Improve error message, give at least one label name.
or better, give all of them

*** missing errors!

failwith "Unix error: %s while executing %s with %s"
      (Unix.error_message err) cmd arg

  I forgot 'spf' but ocaml light says nothing

Unix1.openfile "/dev/cons" [Unix1.O_RDONLY];

  I forgot the perm parameter, but ocaml light said nothing

*** unused variable check 
and the _xxx prefix to invalidate it

*** check result ignored
see in lib_graphics/input/keyboard.ml
I was doing    Event.send ctl.chan buf.[i];
but this is not unit!

** Misc

*** old C style proto

https://github.com/ocaml/ocaml/pull/11764
see also many fixes in https://ocaml.org/releases/4.14.2#runtime-system
so 4.14 would compile with recent gcc that is stricter

*** license part1
commit cc0f32b05439bb7018e8ad62a54d6371b01aab9f
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Wed Nov 17 18:59:06 1999 +0000

    Changement de la licence

LGPL for byterun/

*** other

c4fb76de04783aea39a97b9279ea7adf5fdacfa8
Fix: bug dans le calcul de la longueur max d'une chaine.

ce301ce8fb46ce57a19a1323c9a6e6959da4d749
OFFSETREF met () dans l'accu.

3402009ef3e42d2977bbe0be6bb11841bd3445b8
Faute d'orthographe sur un ident dans intern_from_string.


commit ddd99c7e5d2f0f8e7364e8521fa7e8308999344e
Author: Xavier Leroy <xavier.leroy@inria.fr>
Date:   Tue Aug 28 14:47:48 2001 +0000

    Chargement dynamique de primitives C
?

commit ddc93821b88710566a5816f6e3e712bcf8cc3c9d
ajout assert pour eviter le bug d'alignement des racines
also need diff that introduce compact.c?

commit 0f45531954cadaa9f19a73944e8f9574f5fc08ee
Author: Damien Doligez <damien.doligez-inria.fr>
Date:   Sun Oct 29 17:36:44 2000 +0000

    passage a ANSI C -> suppression bcopy et memmov
