(*s: asmcomp/coloring.mli *)
(*s: copyright header *)
(***********************************************************************)
(*                                                                     *)
(*                           Objective Caml                            *)
(*                                                                     *)
(*            Xavier Leroy, projet Cristal, INRIA Rocquencourt         *)
(*                                                                     *)
(*  Copyright 1996 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)
(*e: copyright header *)

(*s: signature [[Coloring.allocate_registers]] *)
(* Register allocation by coloring of the interference graph *)

val allocate_registers: unit -> unit
(*e: signature [[Coloring.allocate_registers]] *)
(*e: asmcomp/coloring.mli *)
