(*s: asmcomp/scheduling.mli *)
(*s: copyright header *)
(***********************************************************************)
(*                                                                     *)
(*                           Objective Caml                            *)
(*                                                                     *)
(*            Xavier Leroy, projet Cristal, INRIA Rocquencourt         *)
(*                                                                     *)
(*  Copyright 1996 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)
(*e: copyright header *)

(*s: signature Scheduling.fundecl *)
(* Instruction scheduling *)

val fundecl: Linearize.fundecl -> Linearize.fundecl
(*e: signature Scheduling.fundecl *)
(*e: asmcomp/scheduling.mli *)
