(*s: asmcomp/split.mli *)
(*s: copyright header *)
(***********************************************************************)
(*                                                                     *)
(*                           Objective Caml                            *)
(*                                                                     *)
(*            Xavier Leroy, projet Cristal, INRIA Rocquencourt         *)
(*                                                                     *)
(*  Copyright 1996 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)
(*e: copyright header *)

(*s: signature Split.fundecl *)
(* Renaming of registers at reload points to split live ranges. *)

val fundecl: Mach.fundecl -> Mach.fundecl
(*e: signature Split.fundecl *)
(*e: asmcomp/split.mli *)
