# -*- sh -*-
TOP=../../principia
objtype=386
#alt: <$TOP/mkconfig

# need to have 'ocamlc' below compiled with utils/config.ml calling 'pcc'
# instead of 'gcc', and need to have 'pcc' in PATH (from goken)
OCAMLC=/usr/local/bin/ocamlrun /usr/local/bin/ocamlc $CAML_INCLUDES

# need to have libcamlrun.a compiled by plan9 (via pcc, from byterun/ with
# config/plan9.h copied to config/s.h, see byterun/mkfile)
# but also libap.a as libcamlrun.a now depends on libap.a
CAMLLIB=$TOP/ROOT/$objtype/lib/ocaml

default:V: hello.byte

# need main.8 otherwise linker stop immediately as no code is needed
hello.byte: hello.ml
	$OCAMLC -custom -verbose hello.ml -o hello.byte -cclib $CAMLLIB/main.8

%.cmo: %.ml
	$OCAMLC -c -verbose $stem.ml

#%.$O: %.c
#	$CC $CFLAGS -c $stem.c      

clean nuke:V:
	rm -f *.cm* *.byte *.[58]
