TOP=../../principia
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile


OCAMLC=/usr/local/bin/ocamlrun /usr/local/bin/ocamlc $CAML_INCLUDES
OCAMLLEX=/usr/local/bin/ocamlrun /usr/local/bin/ocamllex

default:V: hello.byte

hello.byte: hello.ml
	$OCAMLC -custom -verbose hello.ml -o hello.byte


#LIBS=/usr/local/lib/ocaml/libunix.a
#LIBS=$TOP/ROOT/$objtype/lib/ocaml/libunix.a 
#CAMLLIB=$TOP/ROOT/$objtype/lib/ocaml
#$TOP/$objtype/lib/ocaml/libcamlrun.a
#LIBCAML=/usr/local/lib/ocaml/libcamlrun.a
#LIBUNIX=/usr/local/lib/ocaml/libunix.a

%.cmo: %.ml
	$OCAMLC -c -verbose $stem.ml

# I wanted to use 8c and the regular /lib/libdraw.a, but apparently 
# you can't mix the standard /lib/xxx.a with the /lib/ape/xxx.a
# and ocamlc requires /lib/ape/libap.a in libcamlrun.a so
# I had to switch back to pcc.

CC=pcc
LD=pcc
INCLUDES= -I/usr/local/lib/ocaml
CFLAGS=-FV -c -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE $INCLUDES

%.$O: %.c
	$CC $CFLAGS -c $stem.c      

clean nuke:V:
	rm -f *.cm* *.byte *.[58]
