# -*- sh -*-
# similar to tests/custom/mkfile

TOP=../../../principia
objtype=386
#alt: <$TOP/mkconfig

OCAMLC=/usr/local/bin/ocamlrun /usr/local/bin/ocamlc $CAML_INCLUDES
CAMLLIB=$TOP/ROOT/$objtype/lib/ocaml

default:V: unix.byte

unix.byte: test_unix.ml
	$OCAMLC -verbose unix.cma -custom test_unix.ml -o unix.byte -cclib $CAMLLIB/main.8 -cclib $CAMLLIB/libunix.a


%.cmo: %.ml
	$OCAMLC -c -verbose $stem.ml

#%.$O: %.c
#	$CC $CFLAGS -c $stem.c      

clean nuke:V:
	rm -f *.cm* *.byte *.[58]
