TOP=../../../principia
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile


OCAMLC=/usr/local/bin/ocamlrun /usr/local/bin/ocamlc $CAML_INCLUDES
OCAMLLEX=/usr/local/bin/ocamlrun /usr/local/bin/ocamllex

default:V: unix.byte
#hello.byte test_draw.byte

#hello.byte: hello.ml
#	$OCAMLC -verbose hello.ml -o hello.byte


LIBS=/usr/local/lib/ocaml/libunix.a
#LIBS=$TOP/ROOT/$objtype/lib/ocaml/libunix.a 
#CAMLLIB=$TOP/ROOT/$objtype/lib/ocaml
#$TOP/$objtype/lib/ocaml/libcamlrun.a

unix.byte: test_unix.ml
	$OCAMLC -verbose unix.cma -custom  test_unix.ml -o unix.byte $LIBS


LIBCAML=/usr/local/lib/ocaml/libcamlrun.a
LIBUNIX=/usr/local/lib/ocaml/libunix.a

#test_draw.byte: draw.cmo draw.$O test_draw.cmo 
#	$OCAMLC -verbose -custom unix.cma $prereq $LIBUNIX $LIBCAML -o $target

# manual .depend
#test_draw.cmo: draw.cmo

%.cmo: %.ml
	$OCAMLC -c -verbose $stem.ml

# I wanted to use 8c and the regular /lib/libdraw.a, but apparently 
# you can't mix the standard /lib/xxx.a with the /lib/ape/xxx.a
# and ocamlc requires /lib/ape/libap.a in libcamlrun.a so
# I had to switch back to pcc.

CC=pcc
LD=pcc
INCLUDES= -I/usr/local/lib/ocaml
CFLAGS=-FV -c -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE $INCLUDES

%.$O: %.c
	$CC $CFLAGS -c $stem.c      

clean nuke:V:
	rm -f *.cm* *.byte *.[58]
