# -*- sh -*-

TOP=../../principia
<$TOP/mkconfig
<$TOP/mkfiles/$objtype/mkfile

LIB=libthreads.a

OFILES=scheduler.$O

CFLAGS_EXTRA=-I../../byterun

<$TOP/mkfiles/mklib

CC=pcc
LD=pcc
CFLAGS=-FV -c -D_POSIX_SOURCE -D_BSD_EXTENSION -DOS_PLAN9_APE $INCLUDES
LDFLAGS=

ROOT=$TOP/ROOT

install:V: $LIB
	cp $LIB $ROOT/$objtype/lib/ocaml/

clean:
	rm -f *.[58] y.tab.? y.output y.error $CLEANFILES
	rm -f $LIB
