# Including this file assumes you have set the TOP variable

OCAMLC=$(TOP)/byterun/ocamlrun $(TOP)/ocamlc -g -I $(TOP)/stdlib
OCAMLOPT=$(TOP)/byterun/ocamlrun $(TOP)/ocamlopt -I $(TOP)/stdlib
OCAMLRUN=$(TOP)/byterun/ocamlrun
