(*s: ./utils/clflags.ml *)
(*s: copyright header *)
(***********************************************************************)
(*                                                                     *)
(*                           Objective Caml                            *)
(*                                                                     *)
(*            Xavier Leroy, projet Cristal, INRIA Rocquencourt         *)
(*                                                                     *)
(*  Copyright 1996 Institut National de Recherche en Informatique et   *)
(*  Automatique.  Distributed only by permission.                      *)
(*                                                                     *)
(***********************************************************************)
(*e: copyright header *)

(* Command-line parameters *)

(*s: constant Clflags.objfiles *)
let objfiles = ref ([] : string list)   (* .cmo and .cma files *)
(*e: constant Clflags.objfiles *)
(*s: constant Clflags.ccobjs *)
let ccobjs = ref ([] : string list)     (* .o, .a and -lxxx files *)
(*e: constant Clflags.ccobjs *)
(*s: constant Clflags.compile_only *)
let compile_only = ref false            (* -c *)
(*e: constant Clflags.compile_only *)
(*s: constant Clflags.exec_name *)
let exec_name = ref "a.out"             (* -o *)
(*e: constant Clflags.exec_name *)
(*s: constant Clflags.archive_name *)
let archive_name = ref "library.cma"    (* -o *)
(*e: constant Clflags.archive_name *)
(*s: constant Clflags.object_name *)
let object_name = ref ("camlprog" ^ Config.ext_obj) (* -o *)
(*e: constant Clflags.object_name *)
(*s: constant Clflags.include_dirs *)
let include_dirs = ref ([] : string list)(* -I *)
(*e: constant Clflags.include_dirs *)
(*s: constant Clflags.print_types *)
let print_types = ref false             (* -i *)
(*e: constant Clflags.print_types *)
(*s: constant Clflags.make_archive *)
let make_archive = ref false            (* -a *)
(*e: constant Clflags.make_archive *)
(*s: constant Clflags.debug *)
let debug = ref false                   (* -g *)
(*e: constant Clflags.debug *)
(*s: constant Clflags.fast *)
let fast = ref false                    (* -unsafe *)
(*e: constant Clflags.fast *)
(*s: constant Clflags.link_everything *)
let link_everything = ref false         (* -linkall *)
(*e: constant Clflags.link_everything *)
(*s: constant Clflags.custom_runtime *)
let custom_runtime = ref false          (* -custom *)
(*e: constant Clflags.custom_runtime *)
(*s: constant Clflags.output_c_object *)
let output_c_object = ref false         (* -output-obj *)
(*e: constant Clflags.output_c_object *)
(*s: constant Clflags.ccopts *)
let ccopts = ref ([] : string list)     (* -ccopt *)
(*e: constant Clflags.ccopts *)
(*s: constant Clflags.nopervasives *)
let nopervasives = ref false            (* -nopervasives *)
(*e: constant Clflags.nopervasives *)
(*s: constant Clflags.preprocessor *)
let preprocessor = ref(None : string option) (* -pp *)
(*e: constant Clflags.preprocessor *)
(*s: constant Clflags.thread_safe *)
let thread_safe = ref false             (* -thread *)
(*e: constant Clflags.thread_safe *)
(*s: constant Clflags.noassert *)
let noassert = ref false                (* -noassert *)
(*e: constant Clflags.noassert *)
(*s: constant Clflags.verbose *)
let verbose = ref false                 (* -verbose *)
(*e: constant Clflags.verbose *)

let output_c = ref false         (* -output-c *)

(*s: constant Clflags.dump_rawlambda *)
let dump_rawlambda = ref false          (* -drawlambda *)
(*e: constant Clflags.dump_rawlambda *)
(*s: constant Clflags.dump_lambda *)
let dump_lambda = ref false             (* -dlambda *)
(*e: constant Clflags.dump_lambda *)
(*s: constant Clflags.dump_instr *)
let dump_instr = ref false              (* -dinstr *)
(*e: constant Clflags.dump_instr *)

(*s: constant Clflags.keep_asm_file *)
let keep_asm_file = ref false           (* -S *)
(*e: constant Clflags.keep_asm_file *)
(*s: constant Clflags.optimize_for_speed *)
let optimize_for_speed = ref true       (* -compact *)
(*e: constant Clflags.optimize_for_speed *)

(*s: constant Clflags.dump_cmm *)
let dump_cmm = ref false                (* -dcmm *)
(*e: constant Clflags.dump_cmm *)
(*s: constant Clflags.dump_selection *)
let dump_selection = ref false          (* -dsel *)
(*e: constant Clflags.dump_selection *)
(*s: constant Clflags.dump_live *)
let dump_live = ref false               (* -dlive *)
(*e: constant Clflags.dump_live *)
(*s: constant Clflags.dump_spill *)
let dump_spill = ref false              (* -dspill *)
(*e: constant Clflags.dump_spill *)
(*s: constant Clflags.dump_split *)
let dump_split = ref false              (* -dsplit *)
(*e: constant Clflags.dump_split *)
(*s: constant Clflags.dump_scheduling *)
let dump_scheduling = ref false         (* -dscheduling *)
(*e: constant Clflags.dump_scheduling *)
(*s: constant Clflags.dump_interf *)
let dump_interf = ref false             (* -dinterf *)
(*e: constant Clflags.dump_interf *)
(*s: constant Clflags.dump_prefer *)
let dump_prefer = ref false             (* -dprefer *)
(*e: constant Clflags.dump_prefer *)
(*s: constant Clflags.dump_regalloc *)
let dump_regalloc = ref false           (* -dalloc *)
(*e: constant Clflags.dump_regalloc *)
(*s: constant Clflags.dump_reload *)
let dump_reload = ref false             (* -dreload *)
(*e: constant Clflags.dump_reload *)
(*s: constant Clflags.dump_linear *)
let dump_linear = ref false             (* -dlinear *)
(*e: constant Clflags.dump_linear *)
(*s: constant Clflags.keep_startup_file *)
let keep_startup_file = ref false       (* -dstartup *)
(*e: constant Clflags.keep_startup_file *)

(*s: constant Clflags.native_code *)
let native_code = ref false             (* set to true under ocamlopt *)
(*e: constant Clflags.native_code *)

(*s: constant Clflags.inline_threshold *)
let inline_threshold = ref 10
(*e: constant Clflags.inline_threshold *)
(*e: ./utils/clflags.ml *)
