jobs:
  job:
    runs-on: ubuntu-22.04
    container:
      # alt: semgrep/semgrep:develop to live on the edge! but seems dead.
      image: semgrep/semgrep
    #TODO: at some point
    #env:
    #  SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    # ...
    # run: semgrep ci
    steps:
      - uses: actions/checkout@v3
      # Workaround for rootless containers as git operations may fail due to
      # dubious ownership of /__w/ocaml-light
      # ugly: needed because osemgrep doesn't do the git hack in pysemgrep
      - run: |
          git --version
          pwd
          ls
          git config --global --add safe.directory /__w/ocaml-light/ocaml-light
          git -C /__w/ocaml-light/ocaml-light ls-files -z --cached
      # coupling: with Makefile 'make check' target
      - run: semgrep scan --experimental --config semgrep.jsonnet --strict --error

name: semgrep
on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    branches:
      - master
  #schedule:
  #  - cron: 50 15 * * *
