jobs:
  job:
    runs-on: ubuntu-22.04
    container:
      # living on the edge!
      image: semgrep/semgrep:develop
    #TODO: at some point
    #env:
    #  SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    # ...
    # run: semgrep ci
    steps:
      - uses: actions/checkout@v3
      # coupling: with Makefile 'make check' target
      - run: semgrep scan --experimental --config semgrep.jsonnet --strict --error

name: semgrep
on:
  pull_request_target: {}
  workflow_dispatch: null
  push:
    #TODO: Error: [ERROR]: Error: exception Git_wrapper.Git_error("Could not get files from git ls-files: exit 128; command: 'git' '-C' '/__w/ocaml-light/ocaml-light' 'ls-files' '-z' '--cached'")
    branches:
      - mainXXX
  #schedule:
  #  - cron: 50 15 * * *
